controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.25.1"

  ## Name of the ingress class to route through this controller
  ##
  ingressClass: nginx

  replicaCount: 2

  service:
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

    ## Set external traffic policy to: "Local" to preserve source IP on
    ## providers supporting it
    ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
    externalTrafficPolicy: "Local"
